### PR TITLE
@nextcloud/dialogs v4.2.0

### PR DESCRIPTION
**Pull request by Thatoo**
This code builds.
`filePicker.build()` works
but when it reaches to `filePicker.pick()` it doesn't display anything because I get such following path error : 

```
Failed to load the element <script> from « https://zyuno.local/apps/picker/js/picker-vendors-node_modules_path-browserify_index_js-node_modules_nextcloud_dialogs_dist_chunks_Dial-7445f9.js?v=8ddf27581abc54d78b9b ». NotificationsApp.vue:2
Failed to load the element <script> from « https://zyuno.local/apps/picker/js/picker-node_modules_nextcloud_dialogs_dist_legacy_mjs.js?v=48ca7785c8fd63087532 ». NotificationsApp.vue:2
```

it should get script from
`https://zyuno.local/nextcloud/apps/picker/js...` and not `https://zyuno.local/apps/picker/js...`
I don't understand why it forgets `/nextcloud/` in the path looking for scripts files?

In `config/config.php` I indeed have :
`'overwrite.cli.url' => 'https://zyuno.local/nextcloud',`

and everything except that is working.

Thank you for your feedback.

### CODE REVIEW

**Comment by Thatoo** [comment]
Using a nextcloud hosted on a subdomain such as `https://nc.zyuno.local/` instead of a sufolder such as `https://zyuno.local/nextcloud/` allowed me to make more test (this issue would still need to be solved.

**Comment by Thatoo** [comment]
Unfortunately, I get an unsatisfying result with this code 
```
function openFilePicker() {
	const filePicker = getFilePickerBuilder(t('picker', 'Choose a file and start collaborating'))
		.setMultiSelect(false)
		.allowDirectories(true)
		.startAt(lastPath)
		.build()
	console.debug('File picker built successfully')
	console.debug('Attempting to display file picker...')
	filePicker.pick().then((targetPath) => {
		console.debug('File picked:', targetPath)
		onFileSelected(targetPath)
	}).catch((error) => {
		console.error('Error selecting file:', error)
	})
}
```
replacing 
```
function openFilePicker() {
	OC.dialogs.filepicker(
		t('picker', 'Choose a file and start collaborating'),
		(targetPath) => {
			onFileSelected(targetPath)
		},
		false, null, true, undefined, lastPath
	)
	console.debug('Initializing file picker...')
}
```
image

The window displays weirdly and it doesn't show any file....

**Comment by Thatoo** [comment]
In my web browser consol I have these error : 

```
[Vue warn]: Error in mounted hook (Promise/async): "TypeError: context is undefined"

found in

---> <FilePicker>
       <Root> [vue.runtime.esm.js:4605](webpack:///picker/node_modules/vue/dist/vue.runtime.esm.js)
    VueJS 30
    render legacy.mjs:36
    VueJS 8
    M legacy.mjs:33
    z legacy.mjs:100
    pick index-CRno7JSe.mjs:17
    pick index-CRno7JSe.mjs:10
    openFilePicker main.js:115
    <anonyme> main.js:131
    (Asynchrone : EventListener.handleEvent)
    <anonyme> main.js:122
    <anonyme> picker-main.js:70932
    <anonyme> picker-main.js:70934
TypeError: context is undefined
    request request.js:71
    node_modules NextJS
    get index.js:2
    execute index.js:2
    patchInline index.js:2
    Q index.js:2
    K index.js:2
    H index.js:2
    Ne index.js:2
    Ne index.js:2
    getDirectoryContents index.js:2
    C FilePicker-oSc3I_BN.mjs:876
    loadFiles FilePicker-oSc3I_BN.mjs:887
    node_modules NextJS
    VueJS 25
    render legacy.mjs:36
    VueJS 8
    M legacy.mjs:33
    z legacy.mjs:100
    pick index-CRno7JSe.mjs:17
    pick index-CRno7JSe.mjs:10
    openFilePicker main.js:115
    <anonymous> main.js:131
    EventListener.handleEvent* main.js:122
    <anonymous> picker-main.js:70932
    <anonymous> picker-main.js:70934
[vue.runtime.esm.js:3049](webpack:///picker/node_modules/vue/dist/vue.runtime.esm.js)
[Vue warn]: Error in render: "RangeError: invalid array length"

found in

---> <FileList>
       <NcModal>
         <DialogBase>
           <FilePicker>
             <Root> [vue.runtime.esm.js:4605](webpack:///picker/node_modules/vue/dist/vue.runtime.esm.js)
RangeError: invalid array length
    renderList VueJS
    ot FilePicker-oSc3I_BN.mjs:484
    VueJS 13
    node_modules NextJS
    VueJS 4
    r FilePicker-oSc3I_BN.mjs:459
    node_modules NextJS
    VueJS 25
    render legacy.mjs:36
    VueJS 8
    M legacy.mjs:33
    z legacy.mjs:100
    pick index-CRno7JSe.mjs:17
    pick index-CRno7JSe.mjs:10
    openFilePicker main.js:115
    <anonymous> main.js:131
    EventListener.handleEvent* main.js:122
    <anonymous> picker-main.js:70932
    <anonymous> picker-main.js:70934
```
Any idea how to solve that?

**Comment by Thatoo** [comment]
To solve the styling issue, I tried to add 
`import '@nextcloud/dialogs/style.css'`
below
`import { showError, getFilePickerBuilder } from '@nextcloud/dialogs'`
but I get the following error when I try to build
`  10:8  error  Unable to resolve path to module '@nextcloud/dialogs/style.css'  import/no-unresolved`

**Comment by Thatoo** [comment]
I added `"import/no-unresolved": "off"` to "rules" of .eslintrc.js

Now I have a prettier window thanks to css 

image

but it doesn't display files and I keep having the error in console listed earlier

```
[Vue warn]: Error in mounted hook (Promise/async): "TypeError: context is undefined"
...
[vue.runtime.esm.js:3049](webpack:///picker/node_modules/vue/dist/vue.runtime.esm.js)
[Vue warn]: Error in render: "RangeError: invalid array length"
...
```

**Comment by Thatoo** [comment]
I tried with `lastPath` being initialized at `'/'` or `''` or `null` but it doesn't help. files and directories aren't being displayed and I don't understand why.

**Comment by Thatoo** [comment]
I tried to get inspiration from cookbook then and I tried to update to
"@nextcloud/dialogs": "^5.0.3",
and
"@nextcloud/vue": "^8.3.0",

but when building fails with these errors…

```
ERROR in ./node_modules/@nextcloud/dialogs/dist/index.mjs 5:0-66
Module not found: Error: Package path ./dist/Components/NcDialog.js is not exported from package /var/www/nextcloud/apps/picker/node_modules/@nextcloud/vue (see exports field in /var/www/nextcloud/apps/picker/node_modules/@nextcloud/vue/package.json)
 @ ./src/main.js 6:0-85 64:4-13 80:4-13 94:6-15 99:4-13 104:21-41 106:52-73

ERROR in ./node_modules/@nextcloud/dialogs/dist/index.mjs 6:0-70
Module not found: Error: Package path ./dist/Components/NcNoteCard.js is not exported from package /var/www/nextcloud/apps/picker/node_modules/@nextcloud/vue (see exports field in /var/www/nextcloud/apps/picker/node_modules/@nextcloud/vue/package.json)
 @ ./src/main.js 6:0-85 64:4-13 80:4-13 94:6-15 99:4-13 104:21-41 106:52-73
```

Any idea, any suggestion @provokateurin to help me moving forward?

**Comment by provokateurin** [comment]
Sounds like the components were renamed, checkout https://github.com/nextcloud-libraries/nextcloud-dialogs/tree/v5.0.3/lib/components to see what is available.

**Comment by Thatoo** [comment]
I'm sorry. I really tried to guess what you meant but I didn't understand.
In picker code, there are no trace of `NcDialog` nor `NcNoteCard`.
In https://github.com/nextcloud-libraries/nextcloud-dialogs/tree/v5.0.3/lib/components there are no trace of `NcNoteCard` but I can find `NcNoteCard` mentioned in this file https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/v5.0.3/lib/components/FilePicker/FilePicker.vue
Still I don't see what I can do of this information about building picker failure mentioned above with, in package.json : 
```
  "dependencies": {
    "@nextcloud/auth": "^2.0.0",
    "@nextcloud/axios": "^2.1.0",
    "@nextcloud/dialogs": "^5.0.3",
    "@nextcloud/initial-state": "^2.0.0",
    "@nextcloud/l10n": "^1.4.1",
    "@nextcloud/moment": "^1.1.1",
    "@nextcloud/paths": "^2.1.0",
    "@nextcloud/router": "^2.0.0",
    "@nextcloud/vue": "^8.3.0",
    "vue": "^2.7.15",
    "vue-material-design-icons": "^5.2.0"
  },
```

**Comment by provokateurin** [comment]
Ah yeah I didn't check. There must be a version mismatch between `@nextcloud/vue` and `@nextcloud/dialogs`. Because you updated the later you also need to update the former to a version that is compatible.

**Comment by Thatoo** [comment]
`@nextcloud/dialogs` v 5.0.3 has been released on 27/11/2023.
`@nextcloud/vue` v 8.3.0 was released on 30/11/2023
I then tried with v 8.2.0 released on 17/11/2023 (same error) and v 8.4.0 released on 27/12/2023 (same error).

And well, if I choose these two version `@nextcloud/dialogs` v 5.0.3 and `@nextcloud/vue` v 8.3.0 is because I copied it from [cookbook app](https://github.com/nextcloud/cookbook/blob/master/package.json) which is using [getFilePickerBuilder](https://github.com/nextcloud/cookbook/blob/5068815f3dfaf84ee0a4b2b053022e9f3cc074ac/src/components/Modals/SettingsDialog.vue#L349-L385)

**Comment by Thatoo** [comment]
I tried with the latest release @nextcloud/dialogs v 5.3.5 and @nextcloud/vue v 8.15.0, and it fully works!
Thank you @provokateurin for your help and patience.

I'll probably make a new and cleaner PR.

**Comment by provokateurin** [comment]
You could just squash all commits into one, then it's clean again.

**Comment by Thatoo** [comment]
Right now, I just wonder how to remove this "+New" button that allow to add a new folder and we don't need/want in this picker app...
image

**Comment by Thatoo** [comment]
Closing in favor of https://github.com/nextcloud/picker/pull/45

**Pull request closed without merging**
